### ISSUE TITLE
Hacktoberfest: Recommending better gitignore

### ISSUE THREAD

**Issue by realapril** [bacloud14/opacityontop#3]
Current gitignore will cause several crashes when other people opens the project from android studio after cloning.
Please kindly accept the updated gitignore template from the GitHub’s collection.

**Comment by realapril** [comment]
Also actually your repository is not participating in Hacktoberfest. You should add the "hacktoberfest" topic to the repository if you wish to participate, Hacktoberfest official website is counting your repository as a Ineligible Repository.

**Comment by bacloud14** [comment]
Thanks for contribution, nice. Ok then I will add it later

**Comment by bacloud14** [comment]
Hey @realapril , I merged , would you tell why is that ? I saw other files/folder to ignore, but why it would crash ..
thanks

**Comment by bacloud14** [comment]
Any follow up? Thanks I would like to know about..
